"""Indian stock universe — symbols, names, sectors for Nifty 50/100/Midcap/Smallcap."""
from __future__ import annotations
from typing import Dict, List

# ── Indices ───────────────────────────────────────────────────
INDICES: Dict[str, str] = {
    "NIFTY 50":      "^NSEI",
    "SENSEX":        "^BSESN",
    "NIFTY BANK":    "^NSEBANK",
    "NIFTY IT":      "^CNXIT",
    "NIFTY MIDCAP":  "NIFTY_MIDCAP_100.NS",
}

# ── Nifty 50 ──────────────────────────────────────────────────
NIFTY50_SYMBOLS: List[str] = [
    "RELIANCE.NS","TCS.NS","HDFCBANK.NS","INFY.NS","ICICIBANK.NS",
    "HINDUNILVR.NS","ITC.NS","SBIN.NS","BHARTIARTL.NS","KOTAKBANK.NS",
    "LT.NS","AXISBANK.NS","ASIANPAINT.NS","MARUTI.NS","SUNPHARMA.NS",
    "TITAN.NS","BAJFINANCE.NS","WIPRO.NS","ULTRACEMCO.NS","NESTLEIND.NS",
    "POWERGRID.NS","NTPC.NS","TECHM.NS","HCLTECH.NS","ONGC.NS",
    "TATAMOTORS.NS","TATASTEEL.NS","JSWSTEEL.NS","ADANIENT.NS","ADANIPORTS.NS",
    "COALINDIA.NS","DIVISLAB.NS","DRREDDY.NS","EICHERMOT.NS","GRASIM.NS",
    "HEROMOTOCO.NS","HINDALCO.NS","INDUSINDBK.NS","M&M.NS","BAJAJFINSV.NS",
    "BAJAJ-AUTO.NS","BPCL.NS","BRITANNIA.NS","CIPLA.NS","APOLLOHOSP.NS",
    "SBILIFE.NS","HDFCLIFE.NS","UPL.NS","TATACONSUM.NS","SHRIRAMFIN.NS",
]

# ── Nifty Next 50 (51–100) ────────────────────────────────────
NIFTY_NEXT50_SYMBOLS: List[str] = [
    "ADANIGREEN.NS","ADANITRANS.NS","AMBUJACEM.NS","AUROPHARMA.NS","BAJAJHLDNG.NS",
    "BANKBARODA.NS","BERGEPAINT.NS","BEL.NS","BOSCHLTD.NS","CANBK.NS",
    "CHOLAFIN.NS","COLPAL.NS","DABUR.NS","DLF.NS","GAIL.NS",
    "GODREJCP.NS","GODREJPROP.NS","HAL.NS","HAVELLS.NS","ICICIPRULI.NS",
    "ICICIGI.NS","INDUSTOWER.NS","IRCTC.NS","JINDALSTEL.NS","LICI.NS",
    "LUPIN.NS","MARICO.NS","MCDOWELL-N.NS","MUTHOOTFIN.NS","NAUKRI.NS",
    "NMDC.NS","OFSS.NS","PAGEIND.NS","PIDILITIND.NS","PIIND.NS",
    "PNB.NS","RECLTD.NS","SAIL.NS","SIEMENS.NS","SRF.NS",
    "TATAPOWER.NS","TORNTPHARM.NS","TRENT.NS","VEDL.NS","VOLTAS.NS",
    "WHIRLPOOL.NS","ZOMATO.NS","ZYDUSLIFE.NS","PERSISTENT.NS","LTIM.NS",
]

# ── Nifty Midcap 150 (full list) ─────────────────────────────
NIFTY_MIDCAP_SYMBOLS: List[str] = [
    "ABCAPITAL.NS","ABFRL.NS","ALKEM.NS","APLLTD.NS","ASTRAL.NS",
    "ATUL.NS","AUBANK.NS","AWHCL.NS","BALKRISIND.NS","BANDHANBNK.NS",
    "BATAINDIA.NS","BHEL.NS","BIOCON.NS","BLUESTARCO.NS","BRIGADE.NS",
    "CAMS.NS","CANFINHOME.NS","CARBORUNIV.NS","CASTROLIND.NS","CEATLTD.NS",
    "CENTRALBK.NS","CGPOWER.NS","CHAMBLFERT.NS","COFORGE.NS","CONCOR.NS",
    "CROMPTON.NS","CUMMINSIND.NS","CYIENT.NS","DALBHARAT.NS","DEEPAKNTR.NS",
    "DELTACORP.NS","DIXON.NS","EDELWEISS.NS","EMAMILTD.NS","ENDURANCE.NS",
    "ENGINERSIN.NS","ESCORTS.NS","EXIDEIND.NS","FEDERALBNK.NS","FINCABLES.NS",
    "FLUOROCHEM.NS","FORTIS.NS","GLENMARK.NS","GMRINFRA.NS","GNFC.NS",
    "GPPL.NS","GRANULES.NS","GRAPHITE.NS","GUJGASLTD.NS","HFCL.NS",
    "HONAUT.NS","IDFCFIRSTB.NS","IEX.NS","IFCI.NS","IIFL.NS",
    "INDIANB.NS","INDIAMART.NS","INDIGO.NS","INOXWIND.NS","IOB.NS",
    "IPCALAB.NS","JKCEMENT.NS","JKLAKSHMI.NS","JKPAPER.NS","JSWENERGY.NS",
    "JUBLFOOD.NS","JUBLINGREA.NS","KAJARIACER.NS","KALPATPOWR.NS","KANSAINER.NS",
    "KEC.NS","KPITTECH.NS","KRBL.NS","LALPATHLAB.NS","LAURUSLABS.NS",
    "LICHSGFIN.NS","LINDEINDIA.NS","LTTS.NS","LUXIND.NS","M&MFIN.NS",
    "MANAPPURAM.NS","MASFIN.NS","MAXHEALTH.NS","MCX.NS","METROPOLIS.NS",
    "MFSL.NS","MOTHERSON.NS","MPHASIS.NS","MRF.NS","NATCOPHARM.NS",
    "NBCC.NS","NIACL.NS","NLCINDIA.NS","OBEROIRLTY.NS","OLECTRA.NS",
    "ORIENTELEC.NS","PGHH.NS","PHOENIXLTD.NS","POLYCAB.NS","PRESTIGE.NS",
    "PVRINOX.NS","RAJESHEXPO.NS","RAMCOCEM.NS","RKFORGE.NS","RITES.NS",
    "ROUTE.NS","SAFARI.NS","SCHAEFFLER.NS","SHYAMMETL.NS","SIGNATURE.NS",
    "SOBHA.NS","SONACOMS.NS","STARHEALTH.NS","SUNTV.NS","SUPREMEIND.NS",
    "SYNGENE.NS","TATACHEM.NS","TATAELXSI.NS","TATATECH.NS","TEAMLEASE.NS",
    "TIINDIA.NS","TIMKEN.NS","TTKPRESTIG.NS","TVSMOTORS.NS","UCOBANK.NS",
    "UJJIVANSFB.NS","UNIONBANK.NS","UBL.NS","VAIBHAVGBL.NS","VBL.NS",
    "VIJAYA.NS","VINATIORGA.NS","WELCORP.NS","WELSPUNLIV.NS","ZEEL.NS",
]

# ── Nifty Smallcap 100 ────────────────────────────────────────
NIFTY_SMALLCAP_SYMBOLS: List[str] = [
    "AARTIDRUGS.NS","AARTIIND.NS","ABBOTINDIA.NS","ACCELYA.NS","AEGISCHEM.NS",
    "AFFLE.NS","AJANTPHARM.NS","AKZOINDIA.NS","ALEMBICLTD.NS","ALKYLAMINE.NS",
    "AMARAJABAT.NS","AMBER.NS","ANGELONE.NS","ANURAS.NS","APTUS.NS",
    "ARVINDFASN.NS","ASAHIINDIA.NS","ASHOKLEY.NS","ASTRAZEN.NS","AVANTIFEED.NS",
    "BASF.NS","BBTC.NS","BFINVEST.NS","BIKAJI.NS","BIRLASOFT.NS",
    "BORORENEW.NS","BSOFT.NS","CAMPUS.NS","CAPLIPOINT.NS","CARYSIL.NS",
    "CCL.NS","CDSL.NS","CENTURYPLY.NS","CERA.NS","CHALET.NS",
    "CHEMCON.NS","CLEAN.NS","CLNINDIA.NS","CMSINFO.NS","CONFIPET.NS",
    "CONTROLPR.NS","CRAFTSMAN.NS","DATAMATICS.NS","DCMSHRIRAM.NS","DELHIVERY.NS",
    "DEVYANI.NS","DHANI.NS","DHANUKA.NS","DODLA.NS","EASEMYTRIP.NS",
    "EIDPARRY.NS","ELGIEQUIP.NS","EPIGRAL.NS","EQUITASBNK.NS","ESABINDIA.NS",
    "ETHOSLTD.NS","FINEORG.NS","FINPIPE.NS","FINOFINANCE.NS","FLAIR.NS",
    "GAEL.NS","GALAXYSURF.NS","GARFIBRES.NS","GESHIP.NS","GHCL.NS",
    "GICRE.NS","GILLETTE.NS","GLAND.NS","GLAXO.NS","GLOBUSSPR.NS",
    "GMMPFAUDLR.NS","GODFRYPHLP.NS","GPIL.NS","GRINDWELL.NS","GUJALKALI.NS",
    "HAPPSTMNDS.NS","HARDWYN.NS","HBLPOWER.NS","HERITGFOOD.NS","HIKAL.NS",
    "HINDCOPPER.NS","HINDPETRO.NS","HOMEFIRST.NS","HUDCO.NS","IBREALEST.NS",
    "ICIL.NS","IDFC.NS","IGPL.NS","IIFLSEC.NS","IMAGICAA.NS",
    "IMFA.NS","INDIACEM.NS","INDIGOPNTS.NS","INDSWFTLAB.NS","INFIBEAM.NS",
    "INOXGREEN.NS","INTELLECT.NS","IONEXCHANG.NS","IRB.NS","IRCON.NS",
    "JBCHEPHARM.NS","JBMA.NS","JMFINANCIL.NS","JTEKTINDIA.NS","KFINTECH.NS",
    "KIMS.NS","KNRCON.NS","KOLTEPATIL.NS","KPRMILL.NS","LAXMIMACH.NS",
    "LEMONTREE.NS","MAPMYINDIA.NS","MARKSANS.NS","MEDANTA.NS","MIDHANI.NS",
    "MMTC.NS","MOIL.NS","MSTCLTD.NS","NAVA.NS","NAVINFLUOR.NS",
    "NESCO.NS","NETWORK18.NS","NEWGEN.NS","NUVOCO.NS","OCCL.NS",
    "ONMOBILE.NS","ORIENTCEM.NS","PANAMAPET.NS","PARADEEP.NS","PATELENG.NS",
    "PCBL.NS","PENIND.NS","PFIZER.NS","PNBHOUSING.NS","POLYMED.NS",
    "PRAJIND.NS","PRINCEPIPE.NS","PRUDENT.NS","QUESS.NS","RADICO.NS",
    "RAILTEL.NS","RAINBOW.NS","RALLIS.NS","RBLBANK.NS","REDINGTON.NS",
    "RHIM.NS","ROSSARI.NS","RPGLIFE.NS","RPOWER.NS","SAGCEM.NS",
    "SAPPHIRE.NS","SAREGAMA.NS","SBFC.NS","SEQUENT.NS","SHARDACROP.NS",
    "SHILPAMED.NS","SHOPERSTOP.NS","SIGACHI.NS","SKIPPER.NS","SOLARA.NS",
    "SPANDANA.NS","SPARC.NS","STLTECH.NS","SUBROS.NS","SUDARSCHEM.NS",
    "SUMICHEM.NS","SURYAROSNI.NS","SUVENPHAR.NS","SYMPHONY.NS","TANLA.NS",
    "TATAINVEST.NS","TCIEXP.NS","TCNSBRANDS.NS","TDPOWERSYS.NS","THYROCARE.NS",
    "TINPLATE.NS","TITAGARH.NS","UNIPARTS.NS","UTIAMC.NS","VARROC.NS",
    "VGUARD.NS","VIDHIING.NS","VIPIND.NS","VMART.NS","VSTIND.NS",
    "WABAG.NS","WEBELSOLAR.NS","XCHANGING.NS","YATHARTH.NS","ZENSARTECH.NS",
]

# ── Extra popular NSE stocks (new-age, PSU, sectoral) ─────────
NIFTY_EXTRA_SYMBOLS: List[str] = [
    # New-age tech
    "PAYTM.NS","NYKAA.NS","POLICYBZR.NS","CARTRADE.NS","DELHIVERY.NS",
    "MAMAEARTH.NS","IXIGO.NS","SWIGGY.NS","FIRSTCRY.NS","AWFIS.NS",
    # PSU Banks
    "BANKINDIA.NS","MAHABANK.NS","INDIANB.NS","UCOBANK.NS","CENTRALBK.NS",
    "UNIONBANK.NS","CANBK.NS","BANKBARODA.NS","PNB.NS","SBIN.NS",
    # PSU others
    "RVNL.NS","IRFC.NS","IREDA.NS","SJVN.NS","NHPC.NS",
    "RECLTD.NS","PFC.NS","MOIL.NS","NALCO.NS","HINDCOPPER.NS",
    "MIDHANI.NS","BEML.NS","GRSE.NS","COCHINSHIP.NS","MAZAGON.NS",
    # Defence
    "HAL.NS","BEL.NS","PARAS.NS","DATAPATTNS.NS","IDEAFORGE.NS",
    # Renewables
    "ADANIGREEN.NS","TATAPOWER.NS","GREENPANEL.NS","WEBSOL.NS","WAAREEENER.NS",
    "INOXWIND.NS","SUZLON.NS","RPOWER.NS","TORNTPOWER.NS","CESC.NS",
    # Hospitality/Travel
    "INDHOTEL.NS","EIHOTEL.NS","LEMONTREE.NS","CHALET.NS","MAHINDCIE.NS",
    # Agro/Fertilizer
    "CHAMBLFERT.NS","GNFC.NS","GSFC.NS","COROMANDEL.NS","RALLIS.NS",
    "EIDPARRY.NS","KRBL.NS","AVANTIFEED.NS","GODREJAGRO.NS","DHANUKA.NS",
    # Textiles
    "PAGEIND.NS","WELSPUNLIV.NS","TRIDENT.NS","VARDHMAN.NS","RAYMOND.NS",
    "ARVIND.NS","NIITLTD.NS","GOKEX.NS","SPENTEX.NS","SUTLEJ.NS",
    # Logistics
    "BLUEDART.NS","GATI.NS","TCIEXP.NS","MAHLOG.NS","VRL.NS",
    # Media
    "SUNTV.NS","ZEEL.NS","NETWORK18.NS","PVRINOX.NS","SAREGAMA.NS",
    # Retail
    "DMART.NS","VMART.NS","SHOPERSTOP.NS","TRENT.NS","ABFRL.NS",
    # Specialty Chem
    "DEEPAKNTR.NS","AAVAS.NS","CLEAN.NS","NAVINFLUOR.NS","FLUOROCHEM.NS",
    "ALKYLAMINE.NS","FINEORG.NS","VINATIORGA.NS","SUDARSCHEM.NS","ATUL.NS",
]

# ── NSE Extended Universe (~900 additional stocks) ────────────
NSE_EXTENDED_SYMBOLS: List[str] = [
    # Banking & Finance
    "DCBBANK.NS","KARNATAKA.NS","SOUTHBANK.NS","LAKSHVILAS.NS","UJJIVAN.NS",
    "SURYODAY.NS","ESAFSFB.NS","UTKARSHBNK.NS","JSFB.NS","NAINITAL.NS",
    "KARURVYSYA.NS","TAMILNAD.NS","CITYUNIONB.NS","DHANLAXMI.NS","KVBBANK.NS",
    "SBIN.NS","AUBANK.NS","FINOLEXIND.NS","CREDITACC.NS","ARMANFIN.NS",
    "BAJAJHFL.NS","CANFINHOME.NS","GRUH.NS","HOMEFIRST.NS","APTUS.NS",
    "AAVAS.NS","REPCO.NS","CHOLAHLDNG.NS","SUNDARMFIN.NS","MAHINDCIE.NS",
    "MUTHOOTMF.NS","MANAPPURAM.NS","IIFL.NS","IIFLSEC.NS","JMFINANCIL.NS",
    "MOTILALOFS.NS","GEOJITFSL.NS","SHAREINDIA.NS","SMCGLOBAL.NS","ICICIBANK.NS",
    "5PAISA.NS","NUVAMA.NS","ANAND.NS","EMKAY.NS","DOLAT.NS",
    # IT & Tech
    "NIITTECH.NS","HEXAWARE.NS","MASTEK.NS","SONATSOFTW.NS","RATEGAIN.NS",
    "TATAELXSI.NS","KPITTECH.NS","LTTS.NS","CYIENT.NS","MPHASIS.NS",
    "NIIT.NS","APTECH.NS","CMSINFO.NS","DATAMATICS.NS","SAKSOFT.NS",
    "ZENSAR.NS","INFOBEAN.NS","NUCLEUS.NS","TATATECH.NS","PERSISTENT.NS",
    "COFORGE.NS","NEWGEN.NS","INTELLECT.NS","TANLA.NS","ONMOBILE.NS",
    "ROUTE.NS","STLTECH.NS","XCHANGING.NS","BIRLASOFT.NS","HAPPSTMNDS.NS",
    "AFFLE.NS","MAPMYINDIA.NS","INDIAMART.NS","NAUKRI.NS","JUSTDIAL.NS",
    "INFIBEAM.NS","RPOWER.NS","RAILTEL.NS","REDINGTON.NS","COMPUSOFT.NS",
    "ECLERX.NS","KSOLVES.NS","LATENTVIEW.NS","TATACOMM.NS","HCLTECH.NS",
    # Pharma & Healthcare
    "ALEMBICLTD.NS","ALKEM.NS","AJANTPHARM.NS","ASTRAZEN.NS","ABBOTINDIA.NS",
    "CAPLIPOINT.NS","CLNINDIA.NS","DIVI.NS","ERIS.NS","GLAND.NS",
    "GLAXO.NS","GRANULES.NS","GLENMARK.NS","HIKAL.NS","INDSWFTLAB.NS",
    "IPCALAB.NS","JBCHEPHARM.NS","LAURUSLABS.NS","LUPIN.NS","MARKSANS.NS",
    "NATCOPHARM.NS","NIACL.NS","PFIZER.NS","RPGLIFE.NS","SEQUENT.NS",
    "SHILPAMED.NS","SIGACHI.NS","SOLARA.NS","SPARC.NS","SUVENPHAR.NS",
    "THYROCARE.NS","TORNTPHARM.NS","WINDLAS.NS","ZYDUSLIFE.NS","BIOCON.NS",
    "LALPATHLAB.NS","METROPOLIS.NS","MEDANTA.NS","RAINBOW.NS","YATHARTH.NS",
    "FORTIS.NS","MAXHEALTH.NS","KIMS.NS","POLYMED.NS","SUVEN.NS",
    "SUNPHARMA.NS","DRREDDY.NS","CIPLA.NS","DIVISLAB.NS","APOLLOHOSP.NS",
    "AUROPHARMA.NS","APLLTD.NS","SYNGENE.NS","RPGLIFE.NS","WOCKPHARMA.NS",
    # Auto & Auto Ancillary
    "AMARAJABAT.NS","ASAHIINDIA.NS","BALKRISIND.NS","BOSCHLTD.NS","CEATLTD.NS",
    "ENDURANCE.NS","ESCORTS.NS","EXIDEIND.NS","GABRIEL.NS","GREENPANEL.NS",
    "JTEKTINDIA.NS","LUMAXTECH.NS","MAHINDCIE.NS","MINDAIND.NS","MOTHERSON.NS",
    "MRF.NS","SUBROS.NS","SUPRAJIT.NS","TIINDIA.NS","TIMKEN.NS",
    "TVSSRICHAK.NS","UNIPARTS.NS","VARROC.NS","WABCO.NS","WHEELS.NS",
    "CRAFTSMAN.NS","RKFORGE.NS","SCHAEFFLER.NS","SONACOMS.NS","SWARAJENG.NS",
    "TATAMOTORS.NS","MARUTI.NS","HEROMOTOCO.NS","BAJAJ-AUTO.NS","EICHERMOT.NS",
    "TVSMOTORS.NS","OLECTRA.NS","SMLISUZU.NS","ASHOKLEY.NS","FORCEMOT.NS",
    "MAHLOG.NS","CARTRADE.NS","STARBUS.NS","HINDMOTORS.NS","PREMIEREXP.NS",
    # Cement & Construction
    "AMBUJACEM.NS","ULTRACEMCO.NS","GRASIM.NS","DALBHARAT.NS","JKCEMENT.NS",
    "JKLAKSHMI.NS","NUVOCO.NS","ORIENTCEM.NS","RAMCOCEM.NS","SAGCEM.NS",
    "SHREECEM.NS","STARCEMENT.NS","HEIDELBERG.NS","BIRLACORPN.NS","INDIACEM.NS",
    "KNRCON.NS","PATELENG.NS","NBCC.NS","ENGINERSIN.NS","IRCON.NS",
    "RVNL.NS","HGINFRA.NS","PNC.NS","GPPL.NS","GMRINFRA.NS",
    "BRIGADE.NS","DLF.NS","GODREJPROP.NS","OBEROIRLTY.NS","PRESTIGE.NS",
    "SOBHA.NS","KOLTEPATIL.NS","NESCO.NS","PHOENIXLTD.NS","IBREALEST.NS",
    "MAHLIFE.NS","SUNTECK.NS","LODHA.NS","SIGNATURE.NS","KEYSTONE.NS",
    # Chemicals & Specialty
    "AARTI.NS","AARTIIND.NS","AEGISCHEM.NS","ALKYLAMINE.NS","ATUL.NS",
    "BASF.NS","CHEMCON.NS","CLEAN.NS","DCMSHRIRAM.NS","DEEPAKNTR.NS",
    "EPIGRAL.NS","FINEORG.NS","FLUOROCHEM.NS","GUJALKALI.NS","HIKAL.NS",
    "IONEXCHANG.NS","NAVINFLUOR.NS","OCCL.NS","PANAMAPET.NS","PARADEEP.NS",
    "PCBL.NS","PIDILITIND.NS","ROSSARI.NS","SUDARSCHEM.NS","SUMICHEM.NS",
    "VINATIORGA.NS","VINDHYATEL.NS","TATACHEM.NS","GNFC.NS","GSFC.NS",
    "CHAMBLFERT.NS","COROMANDEL.NS","RALLIS.NS","EIDPARRY.NS","PIIND.NS",
    "UPL.NS","DHANUKA.NS","SHARDACROP.NS","BAYER.NS","INSECTICID.NS",
    "GHCL.NS","TRONOX.NS","NOCIL.NS","IGPL.NS","GAEL.NS",
    # Power & Energy
    "ADANIGREEN.NS","ADANITRANS.NS","CESC.NS","INOXWIND.NS","IEX.NS",
    "JSWENERGY.NS","KALPATPOWR.NS","NHPC.NS","NLCINDIA.NS","NTPC.NS",
    "POWERGRID.NS","RPOWER.NS","SJVN.NS","SUZLON.NS","TATAPOWER.NS",
    "TORNTPOWER.NS","WAAREEENER.NS","WEBSOL.NS","WEBELSOLAR.NS","IREDA.NS",
    "NAVA.NS","INOXGREEN.NS","GREENKO.NS","ACME.NS","GENSOL.NS",
    "ONGC.NS","BPCL.NS","GAIL.NS","RELIANCE.NS","IOC.NS",
    "HINDPETRO.NS","MRPL.NS","CHENNPETRO.NS","GULFOILLUB.NS","CASTROLIND.NS",
    "GUJGASLTD.NS","IGL.NS","MGL.NS","ATGL.NS","GSPL.NS",
    # Metal & Mining
    "HINDALCO.NS","JSWSTEEL.NS","TATASTEEL.NS","SAIL.NS","VEDL.NS",
    "NMDC.NS","COALINDIA.NS","MOIL.NS","NALCO.NS","HINDCOPPER.NS",
    "JINDALSTEL.NS","WELCORP.NS","RATNAMANI.NS","MAHINDCIE.NS","GRAPHITE.NS",
    "GPIL.NS","SHYAMMETL.NS","TINPLATE.NS","IMFA.NS","NAVA.NS",
    "MIDHANI.NS","MSTCLTD.NS","MMTC.NS","KIOCL.NS","GMDC.NS",
    "SANDUMA.NS","MANGLMCEM.NS","HLEGLAS.NS","GRINDWELL.NS","CARBORUNIV.NS",
    # Capital Goods & Engineering
    "ABB.NS","BHEL.NS","CGPOWER.NS","CUMMINSIND.NS","ELGIEQUIP.NS",
    "ESABINDIA.NS","GRINDWELL.NS","HAVELLS.NS","HONAUT.NS","KEC.NS",
    "LAXMIMACH.NS","LINDEINDIA.NS","PENIND.NS","POLYCAB.NS","PRAJIND.NS",
    "RHIM.NS","RKFORGE.NS","SCHAEFFLER.NS","SIEMENS.NS","SKIPPER.NS",
    "TDPOWERSYS.NS","TITAGARH.NS","VOLTAMP.NS","WABAG.NS","THERMAX.NS",
    "AIAENG.NS","GMMPFAUDLR.NS","ISGEC.NS","JYOTISTRUC.NS","KALPATPOWR.NS",
    "BEML.NS","BDL.NS","DATAPATTNS.NS","IDEAFORGE.NS","GRSE.NS",
    "COCHINSHIP.NS","MAZAGON.NS","HAL.NS","BEL.NS","MTAR.NS",
    # FMCG & Consumer
    "BRITANNIA.NS","COLPAL.NS","DABUR.NS","EMAMILTD.NS","GODREJCP.NS",
    "HINDUNILVR.NS","ITC.NS","MARICO.NS","NESTLEIND.NS","TATACONSUM.NS",
    "BIKAJI.NS","DODLA.NS","HERITGFOOD.NS","KRBL.NS","AVANTIFEED.NS",
    "VSTIND.NS","RADICO.NS","MCDOWELL-N.NS","GLOBUSSPR.NS","GODFRYPHLP.NS",
    "GILLETTE.NS","PGHH.NS","JYOTHYLAB.NS","BAJAJCON.NS","ZYDUSWELL.NS",
    "PATANJALI.NS","HATSUN.NS","PARAG.NS","KWALITY.NS","VADILALIND.NS",
    # Textiles & Apparel
    "ARVIND.NS","ARVINDFASN.NS","GARFIBRES.NS","KPRMILL.NS","PAGEIND.NS",
    "RAYMOND.NS","SAPPHIRE.NS","SUTLEJ.NS","TCNSBRANDS.NS","TRIDENT.NS",
    "VARDHMAN.NS","WELSPUNLIV.NS","VIPIND.NS","LUXIND.NS","DOLLAR.NS",
    "RUPA.NS","NITIN.NS","SPENTEX.NS","GOKEX.NS","NIITLTD.NS",
    # Retail & Consumer Discretionary
    "DMART.NS","VMART.NS","SHOPERSTOP.NS","TRENT.NS","ABFRL.NS",
    "NYKAA.NS","FIRSTCRY.NS","CAMPUS.NS","BATAINDIA.NS","RELAXO.NS",
    "METROBRAND.NS","KHADIM.NS","LIBERTY.NS","BATA.NS","LEVIS.NS",
    "TITAN.NS","KALYANKJIL.NS","SENCO.NS","THANGAMAYL.NS","RAJESHEXPO.NS",
    # Logistics & Transport
    "BLUEDART.NS","CONCOR.NS","DELHIVERY.NS","GATI.NS","MAHLOG.NS",
    "TCIEXP.NS","VRL.NS","ALLCARGO.NS","AEGISLOG.NS","TVSSCS.NS",
    "SNOWMAN.NS","COLDCHAIN.NS","XPRESSBEES.NS","SPOTON.NS","DTDC.NS",
    "IRCTC.NS","INDIGO.NS","SPICEJET.NS","AIRINDIA.NS","AKASAAIR.NS",
    # Media & Entertainment
    "SUNTV.NS","ZEEL.NS","NETWORK18.NS","PVRINOX.NS","SAREGAMA.NS",
    "TIPS.NS","EROS.NS","BALAJITELE.NS","TVTODAY.NS","JAGRAN.NS",
    "DBCORP.NS","HTMEDIA.NS","NDTV.NS","SUNCLAYLTD.NS","IMAGICAA.NS",
    # Hospitality & Travel
    "INDHOTEL.NS","EIHOTEL.NS","LEMONTREE.NS","CHALET.NS","MAHINDCIE.NS",
    "TAJGVK.NS","ORIENTHOT.NS","KAMAT.NS","WONDERLA.NS","MHRIL.NS",
    "EASEMYTRIP.NS","IXIGO.NS","YATRA.NS","THOMASCOOK.NS","COX.NS",
    # Telecom
    "BHARTIARTL.NS","INDUSTOWER.NS","TATACOMM.NS","HFCL.NS","STLTECH.NS",
    "VINDHYATEL.NS","RAILTEL.NS","BSNL.NS","MTNL.NS","ONMOBILE.NS",
    # Real Estate
    "DLF.NS","GODREJPROP.NS","OBEROIRLTY.NS","PRESTIGE.NS","SOBHA.NS",
    "BRIGADE.NS","KOLTEPATIL.NS","PHOENIXLTD.NS","IBREALEST.NS","NESCO.NS",
    "MAHLIFE.NS","SUNTECK.NS","LODHA.NS","SIGNATURE.NS","KEYSTONE.NS",
    "ANANTRAJ.NS","OMAXE.NS","PARSVNATH.NS","UNITECH.NS","HDIL.NS",
    # Insurance
    "SBILIFE.NS","HDFCLIFE.NS","ICICIPRULI.NS","ICICIGI.NS","LICI.NS",
    "STARHEALTH.NS","NIACL.NS","GICRE.NS","POLICYBZR.NS","MFSL.NS",
    # New Age / Fintech
    "PAYTM.NS","POLICYBZR.NS","CARTRADE.NS","MAMAEARTH.NS","IXIGO.NS",
    "SWIGGY.NS","AWFIS.NS","ZOMATO.NS","NYKAA.NS","FIRSTCRY.NS",
    "INFIBEAM.NS","EASEMYTRIP.NS","JUSTDIAL.NS","INDIAMART.NS","RATEGAIN.NS",
    # Pipes & Wires
    "ASTRAL.NS","FINOLEXIND.NS","PRINCEPIPE.NS","SUPREMEIND.NS","FINOLEX.NS",
    "POLYCAB.NS","KEI.NS","HAVELLS.NS","VGUARD.NS","SURYAROSNI.NS",
    # Paints
    "ASIANPAINT.NS","BERGEPAINT.NS","KANSAINER.NS","INDIGOPNTS.NS","AKZOINDIA.NS",
    "SHALPAINTS.NS","JKLAKSHMI.NS","ORIENTELEC.NS","SHEELA.NS","PIDILITIND.NS",
    # Miscellaneous
    "AARTIDRUGS.NS","ACCELYA.NS","AMBER.NS","ANURAS.NS","BBTC.NS",
    "BFINVEST.NS","BORORENEW.NS","BSOFT.NS","CARYSIL.NS","CCL.NS",
    "CONFIPET.NS","CONTROLPR.NS","DHANI.NS","EDELWEISS.NS","ETHOSLTD.NS",
    "FLAIR.NS","GALAXYSURF.NS","HARDWYN.NS","HBLPOWER.NS","ICIL.NS",
    "IFCI.NS","IMAGICAA.NS","JBMA.NS","JUBLINGREA.NS","LUXIND.NS",
    "MASFIN.NS","NUVOCO.NS","PRUDENT.NS","QUESS.NS","SBFC.NS",
    "SPANDANA.NS","TEAMLEASE.NS","UJJIVANSFB.NS","VAIBHAVGBL.NS","VIJAYA.NS",
    "AWHCL.NS","DELTACORP.NS","FINCABLES.NS","GPPL.NS","IIFLSEC.NS",
    "JKLAKSHMI.NS","JKPAPER.NS","JUBLINGREA.NS","KAJARIACER.NS","LINDEINDIA.NS",
    "NATCOPHARM.NS","NLCINDIA.NS","OLECTRA.NS","ORIENTELEC.NS","PGHH.NS",
    "RAJESHEXPO.NS","RKFORGE.NS","RITES.NS","SAFARI.NS","TATAINVEST.NS",
    "TTKPRESTIG.NS","UBL.NS","UJJIVANSFB.NS","UNIONBANK.NS","VAIBHAVGBL.NS",
]

# ── Universe registry ─────────────────────────────────────────
UNIVERSE_MAP: Dict[str, List[str]] = {
    "nifty50":   NIFTY50_SYMBOLS,
    "nifty100":  NIFTY50_SYMBOLS + NIFTY_NEXT50_SYMBOLS,
    "midcap":    NIFTY_MIDCAP_SYMBOLS,
    "smallcap":  NIFTY_SMALLCAP_SYMBOLS,
    "extended":  list(dict.fromkeys(NSE_EXTENDED_SYMBOLS)),
    "all":       list(dict.fromkeys(
        NIFTY50_SYMBOLS + NIFTY_NEXT50_SYMBOLS +
        NIFTY_MIDCAP_SYMBOLS + NIFTY_SMALLCAP_SYMBOLS +
        NIFTY_EXTRA_SYMBOLS + NSE_EXTENDED_SYMBOLS
    )),
}

# ── Sector map ────────────────────────────────────────────────
SECTOR_MAP: Dict[str, str] = {
    # Nifty 50
    "RELIANCE.NS":"Energy","ONGC.NS":"Energy","BPCL.NS":"Energy",
    "TCS.NS":"IT","INFY.NS":"IT","WIPRO.NS":"IT","HCLTECH.NS":"IT","TECHM.NS":"IT",
    "HDFCBANK.NS":"Banking","ICICIBANK.NS":"Banking","SBIN.NS":"Banking",
    "KOTAKBANK.NS":"Banking","AXISBANK.NS":"Banking","INDUSINDBK.NS":"Banking",
    "HINDUNILVR.NS":"FMCG","ITC.NS":"FMCG","NESTLEIND.NS":"FMCG",
    "BRITANNIA.NS":"FMCG","TATACONSUM.NS":"FMCG",
    "MARUTI.NS":"Auto","TATAMOTORS.NS":"Auto","BAJAJ-AUTO.NS":"Auto",
    "HEROMOTOCO.NS":"Auto","EICHERMOT.NS":"Auto","M&M.NS":"Auto",
    "SUNPHARMA.NS":"Pharma","DRREDDY.NS":"Pharma","CIPLA.NS":"Pharma",
    "DIVISLAB.NS":"Pharma","APOLLOHOSP.NS":"Healthcare",
    "LT.NS":"Infra","ADANIPORTS.NS":"Infra","POWERGRID.NS":"Infra",
    "NTPC.NS":"Power","COALINDIA.NS":"Mining",
    "TATASTEEL.NS":"Metal","JSWSTEEL.NS":"Metal","HINDALCO.NS":"Metal",
    "BAJFINANCE.NS":"Finance","BAJAJFINSV.NS":"Finance","SHRIRAMFIN.NS":"Finance",
    "SBILIFE.NS":"Insurance","HDFCLIFE.NS":"Insurance",
    "ASIANPAINT.NS":"Paints","TITAN.NS":"Consumer","ULTRACEMCO.NS":"Cement",
    "GRASIM.NS":"Cement","ADANIENT.NS":"Conglomerate","UPL.NS":"Agro",
    "BHARTIARTL.NS":"Telecom",
    # Nifty Next 50
    "ADANIGREEN.NS":"Energy","ADANITRANS.NS":"Infra","AMBUJACEM.NS":"Cement",
    "AUROPHARMA.NS":"Pharma","BAJAJHLDNG.NS":"Finance","BANKBARODA.NS":"Banking",
    "BERGEPAINT.NS":"Paints","BEL.NS":"Defence","BOSCHLTD.NS":"Auto",
    "CANBK.NS":"Banking","CHOLAFIN.NS":"Finance","COLPAL.NS":"FMCG",
    "DABUR.NS":"FMCG","DLF.NS":"Realty","GAIL.NS":"Energy",
    "GODREJCP.NS":"FMCG","GODREJPROP.NS":"Realty","HAL.NS":"Defence",
    "HAVELLS.NS":"Consumer","ICICIPRULI.NS":"Insurance","ICICIGI.NS":"Insurance",
    "INDUSTOWER.NS":"Telecom","IRCTC.NS":"Travel","JINDALSTEL.NS":"Metal",
    "LICI.NS":"Insurance","LUPIN.NS":"Pharma","MARICO.NS":"FMCG",
    "MCDOWELL-N.NS":"FMCG","MUTHOOTFIN.NS":"Finance","NAUKRI.NS":"IT",
    "NMDC.NS":"Mining","OFSS.NS":"IT","PAGEIND.NS":"Consumer",
    "PIDILITIND.NS":"Chemicals","PIIND.NS":"Agro","PNB.NS":"Banking",
    "RECLTD.NS":"Finance","SAIL.NS":"Metal","SIEMENS.NS":"Capital Goods",
    "SRF.NS":"Chemicals","TATAPOWER.NS":"Power","TORNTPHARM.NS":"Pharma",
    "TRENT.NS":"Retail","VEDL.NS":"Metal","VOLTAS.NS":"Consumer",
    "WHIRLPOOL.NS":"Consumer","ZOMATO.NS":"Food Tech","ZYDUSLIFE.NS":"Pharma",
    "PERSISTENT.NS":"IT","LTIM.NS":"IT",
    # Midcap
    "ABCAPITAL.NS":"Finance","ABFRL.NS":"Retail","ALKEM.NS":"Pharma",
    "APLLTD.NS":"Pharma","ASTRAL.NS":"Pipes","ATUL.NS":"Chemicals",
    "AUBANK.NS":"Banking","BALKRISIND.NS":"Auto","BANDHANBNK.NS":"Banking",
    "BATAINDIA.NS":"Consumer","BHEL.NS":"Capital Goods","BIOCON.NS":"Pharma",
    "BLUESTARCO.NS":"Consumer","BRIGADE.NS":"Realty","CAMS.NS":"Finance",
    "CANFINHOME.NS":"Finance","CEATLTD.NS":"Auto","CGPOWER.NS":"Capital Goods",
    "COFORGE.NS":"IT","CONCOR.NS":"Logistics","CROMPTON.NS":"Consumer",
    "CUMMINSIND.NS":"Capital Goods","CYIENT.NS":"IT","DALBHARAT.NS":"Cement",
    "DEEPAKNTR.NS":"Chemicals","DIXON.NS":"Consumer","EMAMILTD.NS":"FMCG",
    "ENDURANCE.NS":"Auto","ESCORTS.NS":"Auto","EXIDEIND.NS":"Auto",
    "FEDERALBNK.NS":"Banking","FORTIS.NS":"Healthcare","GLENMARK.NS":"Pharma",
    "GMRINFRA.NS":"Infra","GUJGASLTD.NS":"Energy","IDFCFIRSTB.NS":"Banking",
    "IEX.NS":"Power","INDIAMART.NS":"IT","INDIGO.NS":"Aviation",
    "IPCALAB.NS":"Pharma","JKCEMENT.NS":"Cement","JSWENERGY.NS":"Power",
    "JUBLFOOD.NS":"Food Tech","KAJARIACER.NS":"Consumer","KEC.NS":"Infra",
    "KPITTECH.NS":"IT","LALPATHLAB.NS":"Healthcare","LAURUSLABS.NS":"Pharma",
    "LICHSGFIN.NS":"Finance","LTTS.NS":"IT","M&MFIN.NS":"Finance",
    "MANAPPURAM.NS":"Finance","MAXHEALTH.NS":"Healthcare","MCX.NS":"Finance",
    "METROPOLIS.NS":"Healthcare","MPHASIS.NS":"IT","MRF.NS":"Auto",
    "MOTHERSON.NS":"Auto","NBCC.NS":"Infra","OBEROIRLTY.NS":"Realty",
    "POLYCAB.NS":"Capital Goods","PRESTIGE.NS":"Realty",
    # Smallcap
    "AFFLE.NS":"IT","AJANTPHARM.NS":"Pharma","ANGELONE.NS":"Finance",
    "ASHOKLEY.NS":"Auto","BIRLASOFT.NS":"IT","CDSL.NS":"Finance",
    "CENTURYPLY.NS":"Consumer","DELHIVERY.NS":"Logistics","DEVYANI.NS":"Food Tech",
    "EASEMYTRIP.NS":"Travel","EQUITASBNK.NS":"Banking","GLAND.NS":"Pharma",
    "HAPPSTMNDS.NS":"IT","HINDCOPPER.NS":"Metal","HUDCO.NS":"Finance",
    "IDFC.NS":"Finance","INDIGOPNTS.NS":"Paints","CAMPUS.NS":"Consumer",
    "INOXGREEN.NS":"Power","INTELLECT.NS":"IT","IONEXCHANG.NS":"Chemicals",
    "IRB.NS":"Infra","IRCON.NS":"Infra","JBCHEPHARM.NS":"Pharma",
    "KFINTECH.NS":"Finance","KIMS.NS":"Healthcare","KNRCON.NS":"Infra",
    "KOLTEPATIL.NS":"Realty","KPRMILL.NS":"Textiles","LAXMIMACH.NS":"Capital Goods",
    "LEMONTREE.NS":"Hospitality","MAPMYINDIA.NS":"IT","MARKSANS.NS":"Pharma",
    "MEDANTA.NS":"Healthcare","MIDHANI.NS":"Defence","MMTC.NS":"Trading",
    "MOIL.NS":"Mining","MSTCLTD.NS":"Trading","NAVA.NS":"Power",
    "NAVINFLUOR.NS":"Chemicals","NESCO.NS":"Realty","NETWORK18.NS":"Media",
    "NEWGEN.NS":"IT","NUVOCO.NS":"Cement","OCCL.NS":"Chemicals",
    "ORIENTCEM.NS":"Cement","PANAMAPET.NS":"Chemicals","PARADEEP.NS":"Chemicals",
    "PATELENG.NS":"Infra","PCBL.NS":"Chemicals","PENIND.NS":"Capital Goods",
    "PFIZER.NS":"Pharma","PNBHOUSING.NS":"Finance","POLYMED.NS":"Healthcare",
    "PRAJIND.NS":"Capital Goods","PRINCEPIPE.NS":"Pipes","PRUDENT.NS":"Finance",
    "QUESS.NS":"IT","RADICO.NS":"FMCG","RAILTEL.NS":"IT",
    "RAINBOW.NS":"Healthcare","RALLIS.NS":"Agro","RBLBANK.NS":"Banking",
    "REDINGTON.NS":"IT","RHIM.NS":"Capital Goods","ROSSARI.NS":"Chemicals",
    "RPGLIFE.NS":"Pharma","RPOWER.NS":"Power","SAGCEM.NS":"Cement",
    "SAPPHIRE.NS":"Textiles","SAREGAMA.NS":"Media","SBFC.NS":"Finance",
    "SEQUENT.NS":"Pharma","SHARDACROP.NS":"Agro","SHILPAMED.NS":"Healthcare",
    "SHOPERSTOP.NS":"Retail","SIGACHI.NS":"Pharma","SKIPPER.NS":"Capital Goods",
    "SOLARA.NS":"Pharma","SPANDANA.NS":"Finance","SPARC.NS":"Pharma",
    "STLTECH.NS":"IT","SUBROS.NS":"Auto","SUDARSCHEM.NS":"Chemicals",
    "SUMICHEM.NS":"Chemicals","SURYAROSNI.NS":"Consumer","SUVENPHAR.NS":"Pharma",
    "SYMPHONY.NS":"Consumer","TANLA.NS":"IT","TATAINVEST.NS":"Finance",
    "TCIEXP.NS":"Logistics","TCNSBRANDS.NS":"Retail","TDPOWERSYS.NS":"Capital Goods",
    "THYROCARE.NS":"Healthcare","TINPLATE.NS":"Metal","TITAGARH.NS":"Capital Goods",
    "UNIPARTS.NS":"Auto","UTIAMC.NS":"Finance","VARROC.NS":"Auto",
    "VGUARD.NS":"Consumer","VIDHIING.NS":"Chemicals","VIPIND.NS":"Consumer",
    "VMART.NS":"Retail","VSTIND.NS":"FMCG","WABAG.NS":"Infra",
    "WEBELSOLAR.NS":"Power","XCHANGING.NS":"IT","YATHARTH.NS":"Healthcare",
    "ZENSARTECH.NS":"IT",
    # Extra
    "PAYTM.NS":"Fintech","NYKAA.NS":"Retail","POLICYBZR.NS":"Insurance",
    "CARTRADE.NS":"Auto","MAMAEARTH.NS":"FMCG","IXIGO.NS":"Travel",
    "SWIGGY.NS":"Food Tech","FIRSTCRY.NS":"Retail","AWFIS.NS":"Realty",
    "BANKINDIA.NS":"Banking","MAHABANK.NS":"Banking","UCOBANK.NS":"Banking",
    "RVNL.NS":"Infra","IRFC.NS":"Finance","IREDA.NS":"Finance",
    "SJVN.NS":"Power","NHPC.NS":"Power","PFC.NS":"Finance",
    "NALCO.NS":"Metal","BEML.NS":"Capital Goods","GRSE.NS":"Defence",
    "COCHINSHIP.NS":"Defence","MAZAGON.NS":"Defence","DATAPATTNS.NS":"Defence",
    "IDEAFORGE.NS":"Defence","GREENPANEL.NS":"Consumer","WEBSOL.NS":"Power",
    "WAAREEENER.NS":"Power","SUZLON.NS":"Power","CESC.NS":"Power",
    "INDHOTEL.NS":"Hospitality","EIHOTEL.NS":"Hospitality","MAHINDCIE.NS":"Auto",
    "GSFC.NS":"Chemicals","COROMANDEL.NS":"Agro","GODREJAGRO.NS":"Agro",
    "WELSPUNLIV.NS":"Textiles","TRIDENT.NS":"Textiles","VARDHMAN.NS":"Textiles",
    "RAYMOND.NS":"Textiles","ARVIND.NS":"Textiles","BLUEDART.NS":"Logistics",
    "GATI.NS":"Logistics","MAHLOG.NS":"Logistics","VRL.NS":"Logistics",
    "SUNTV.NS":"Media","ZEEL.NS":"Media","PVRINOX.NS":"Media",
    "DMART.NS":"Retail","AAVAS.NS":"Finance","ALKYLAMINE.NS":"Chemicals",
    "VINATIORGA.NS":"Chemicals","FLUOROCHEM.NS":"Chemicals",
}

# ── Name map ──────────────────────────────────────────────────
NAME_MAP: Dict[str, str] = {
    # Nifty 50
    "RELIANCE.NS":"Reliance Industries","TCS.NS":"Tata Consultancy Services",
    "HDFCBANK.NS":"HDFC Bank","INFY.NS":"Infosys","ICICIBANK.NS":"ICICI Bank",
    "HINDUNILVR.NS":"Hindustan Unilever","ITC.NS":"ITC Ltd","SBIN.NS":"State Bank of India",
    "BHARTIARTL.NS":"Bharti Airtel","KOTAKBANK.NS":"Kotak Mahindra Bank",
    "LT.NS":"Larsen & Toubro","AXISBANK.NS":"Axis Bank","ASIANPAINT.NS":"Asian Paints",
    "MARUTI.NS":"Maruti Suzuki","SUNPHARMA.NS":"Sun Pharmaceutical",
    "TITAN.NS":"Titan Company","BAJFINANCE.NS":"Bajaj Finance",
    "WIPRO.NS":"Wipro","ULTRACEMCO.NS":"UltraTech Cement","NESTLEIND.NS":"Nestle India",
    "POWERGRID.NS":"Power Grid Corp","NTPC.NS":"NTPC Ltd","TECHM.NS":"Tech Mahindra",
    "HCLTECH.NS":"HCL Technologies","ONGC.NS":"ONGC","TATAMOTORS.NS":"Tata Motors",
    "TATASTEEL.NS":"Tata Steel","JSWSTEEL.NS":"JSW Steel","ADANIENT.NS":"Adani Enterprises",
    "ADANIPORTS.NS":"Adani Ports","COALINDIA.NS":"Coal India","DIVISLAB.NS":"Divi's Laboratories",
    "DRREDDY.NS":"Dr. Reddy's","EICHERMOT.NS":"Eicher Motors","GRASIM.NS":"Grasim Industries",
    "HEROMOTOCO.NS":"Hero MotoCorp","HINDALCO.NS":"Hindalco Industries",
    "INDUSINDBK.NS":"IndusInd Bank","M&M.NS":"Mahindra & Mahindra",
    "BAJAJFINSV.NS":"Bajaj Finserv","BAJAJ-AUTO.NS":"Bajaj Auto","BPCL.NS":"BPCL",
    "BRITANNIA.NS":"Britannia Industries","CIPLA.NS":"Cipla","APOLLOHOSP.NS":"Apollo Hospitals",
    "SBILIFE.NS":"SBI Life Insurance","HDFCLIFE.NS":"HDFC Life Insurance",
    "UPL.NS":"UPL Ltd","TATACONSUM.NS":"Tata Consumer Products","SHRIRAMFIN.NS":"Shriram Finance",
    # Nifty Next 50
    "ADANIGREEN.NS":"Adani Green Energy","ADANITRANS.NS":"Adani Transmission",
    "AMBUJACEM.NS":"Ambuja Cements","AUROPHARMA.NS":"Aurobindo Pharma",
    "BAJAJHLDNG.NS":"Bajaj Holdings","BANKBARODA.NS":"Bank of Baroda",
    "BERGEPAINT.NS":"Berger Paints","BEL.NS":"Bharat Electronics",
    "BOSCHLTD.NS":"Bosch Ltd","CANBK.NS":"Canara Bank",
    "CHOLAFIN.NS":"Cholamandalam Finance","COLPAL.NS":"Colgate-Palmolive",
    "DABUR.NS":"Dabur India","DLF.NS":"DLF Ltd","GAIL.NS":"GAIL India",
    "GODREJCP.NS":"Godrej Consumer Products","GODREJPROP.NS":"Godrej Properties",
    "HAL.NS":"Hindustan Aeronautics","HAVELLS.NS":"Havells India",
    "ICICIPRULI.NS":"ICICI Prudential Life","ICICIGI.NS":"ICICI Lombard General",
    "INDUSTOWER.NS":"Indus Towers","IRCTC.NS":"IRCTC","JINDALSTEL.NS":"Jindal Steel & Power",
    "LICI.NS":"LIC of India","LUPIN.NS":"Lupin Ltd","MARICO.NS":"Marico",
    "MCDOWELL-N.NS":"United Spirits","MUTHOOTFIN.NS":"Muthoot Finance",
    "NAUKRI.NS":"Info Edge (Naukri)","NMDC.NS":"NMDC Ltd","OFSS.NS":"Oracle Financial Services",
    "PAGEIND.NS":"Page Industries","PIDILITIND.NS":"Pidilite Industries",
    "PIIND.NS":"PI Industries","PNB.NS":"Punjab National Bank",
    "RECLTD.NS":"REC Ltd","SAIL.NS":"Steel Authority of India",
    "SIEMENS.NS":"Siemens India","SRF.NS":"SRF Ltd","TATAPOWER.NS":"Tata Power",
    "TORNTPHARM.NS":"Torrent Pharmaceuticals","TRENT.NS":"Trent Ltd",
    "VEDL.NS":"Vedanta Ltd","VOLTAS.NS":"Voltas Ltd","WHIRLPOOL.NS":"Whirlpool India",
    "ZOMATO.NS":"Zomato","ZYDUSLIFE.NS":"Zydus Lifesciences",
    "PERSISTENT.NS":"Persistent Systems","LTIM.NS":"LTIMindtree",
    # Midcap
    "ABCAPITAL.NS":"Aditya Birla Capital","ABFRL.NS":"Aditya Birla Fashion",
    "ALKEM.NS":"Alkem Laboratories","APLLTD.NS":"APL Apollo Tubes",
    "ASTRAL.NS":"Astral Ltd","ATUL.NS":"Atul Ltd","AUBANK.NS":"AU Small Finance Bank",
    "BALKRISIND.NS":"Balkrishna Industries","BANDHANBNK.NS":"Bandhan Bank",
    "BATAINDIA.NS":"Bata India","BHEL.NS":"Bharat Heavy Electricals",
    "BIOCON.NS":"Biocon","BLUESTARCO.NS":"Blue Star","BRIGADE.NS":"Brigade Enterprises",
    "CAMS.NS":"CAMS","CANFINHOME.NS":"Can Fin Homes","CEATLTD.NS":"CEAT Ltd",
    "CGPOWER.NS":"CG Power","COFORGE.NS":"Coforge","CONCOR.NS":"Container Corp",
    "CROMPTON.NS":"Crompton Greaves Consumer","CUMMINSIND.NS":"Cummins India",
    "CYIENT.NS":"Cyient","DALBHARAT.NS":"Dalmia Bharat","DEEPAKNTR.NS":"Deepak Nitrite",
    "DIXON.NS":"Dixon Technologies","EMAMILTD.NS":"Emami Ltd","ENDURANCE.NS":"Endurance Technologies",
    "ESCORTS.NS":"Escorts Kubota","EXIDEIND.NS":"Exide Industries",
    "FEDERALBNK.NS":"Federal Bank","FORTIS.NS":"Fortis Healthcare",
    "GLENMARK.NS":"Glenmark Pharmaceuticals","GMRINFRA.NS":"GMR Airports Infra",
    "GUJGASLTD.NS":"Gujarat Gas","IDFCFIRSTB.NS":"IDFC First Bank",
    "IEX.NS":"Indian Energy Exchange","INDIAMART.NS":"IndiaMART InterMESH",
    "INDIGO.NS":"IndiGo (InterGlobe Aviation)","IPCALAB.NS":"IPCA Laboratories",
    "JKCEMENT.NS":"JK Cement","JSWENERGY.NS":"JSW Energy",
    "JUBLFOOD.NS":"Jubilant FoodWorks","KAJARIACER.NS":"Kajaria Ceramics",
    "KEC.NS":"KEC International","KPITTECH.NS":"KPIT Technologies",
    "LALPATHLAB.NS":"Dr Lal PathLabs","LAURUSLABS.NS":"Laurus Labs",
    "LICHSGFIN.NS":"LIC Housing Finance","LTTS.NS":"L&T Technology Services",
    "M&MFIN.NS":"Mahindra & Mahindra Financial","MANAPPURAM.NS":"Manappuram Finance",
    "MAXHEALTH.NS":"Max Healthcare","MCX.NS":"Multi Commodity Exchange",
    "METROPOLIS.NS":"Metropolis Healthcare","MPHASIS.NS":"Mphasis",
    "MRF.NS":"MRF Ltd","MOTHERSON.NS":"Samvardhana Motherson",
    "NBCC.NS":"NBCC India","OBEROIRLTY.NS":"Oberoi Realty",
    "POLYCAB.NS":"Polycab India","PRESTIGE.NS":"Prestige Estates",
    # Smallcap
    "AFFLE.NS":"Affle India","AJANTPHARM.NS":"Ajanta Pharma",
    "ANGELONE.NS":"Angel One","ASHOKLEY.NS":"Ashok Leyland",
    "BIRLASOFT.NS":"Birlasoft","CDSL.NS":"CDSL","CENTURYPLY.NS":"Century Plyboards",
    "DELHIVERY.NS":"Delhivery","DEVYANI.NS":"Devyani International",
    "EASEMYTRIP.NS":"EaseMyTrip","EQUITASBNK.NS":"Equitas Small Finance Bank",
    "GLAND.NS":"Gland Pharma","HAPPSTMNDS.NS":"Happiest Minds",
    "HINDCOPPER.NS":"Hindustan Copper","HUDCO.NS":"HUDCO",
    "IDFC.NS":"IDFC Ltd","INDIGOPNTS.NS":"Indigo Paints","CAMPUS.NS":"Campus Activewear",
    "INOXGREEN.NS":"Inox Green Energy","INTELLECT.NS":"Intellect Design Arena",
    "IONEXCHANG.NS":"Ion Exchange","IRB.NS":"IRB Infrastructure","IRCON.NS":"IRCON International",
    "JBCHEPHARM.NS":"JB Chemicals","KFINTECH.NS":"KFin Technologies",
    "KIMS.NS":"Krishna Institute of Medical Sciences","KNRCON.NS":"KNR Constructions",
    "KOLTEPATIL.NS":"Kolte-Patil Developers","KPRMILL.NS":"KPR Mill",
    "LAXMIMACH.NS":"Laxmi Machine Works","LEMONTREE.NS":"Lemon Tree Hotels",
    "MAPMYINDIA.NS":"MapMyIndia","MARKSANS.NS":"Marksans Pharma",
    "MEDANTA.NS":"Global Health (Medanta)","MIDHANI.NS":"Mishra Dhatu Nigam",
    "MMTC.NS":"MMTC Ltd","MOIL.NS":"MOIL Ltd","MSTCLTD.NS":"MSTC Ltd",
    "NAVA.NS":"NAVA Ltd","NAVINFLUOR.NS":"Navin Fluorine","NESCO.NS":"NESCO Ltd",
    "NETWORK18.NS":"Network18 Media","NEWGEN.NS":"Newgen Software",
    "NUVOCO.NS":"Nuvoco Vistas","OCCL.NS":"Oriental Carbon",
    "ORIENTCEM.NS":"Orient Cement","PANAMAPET.NS":"Panama Petrochem",
    "PARADEEP.NS":"Paradeep Phosphates","PATELENG.NS":"Patel Engineering",
    "PCBL.NS":"PCBL Ltd","PENIND.NS":"Pennar Industries","PFIZER.NS":"Pfizer India",
    "PNBHOUSING.NS":"PNB Housing Finance","POLYMED.NS":"Poly Medicure",
    "PRAJIND.NS":"Praj Industries","PRINCEPIPE.NS":"Prince Pipes",
    "PRUDENT.NS":"Prudent Corporate Advisory","QUESS.NS":"Quess Corp",
    "RADICO.NS":"Radico Khaitan","RAILTEL.NS":"RailTel Corporation",
    "RAINBOW.NS":"Rainbow Children's Medicare","RALLIS.NS":"Rallis India",
    "RBLBANK.NS":"RBL Bank","REDINGTON.NS":"Redington India",
    "RHIM.NS":"RHI Magnesita India","ROSSARI.NS":"Rossari Biotech",
    "RPGLIFE.NS":"RPG Life Sciences","RPOWER.NS":"Reliance Power",
    "SAGCEM.NS":"Sagar Cements","SAPPHIRE.NS":"Sapphire Foods",
    "SAREGAMA.NS":"Saregama India","SBFC.NS":"SBFC Finance",
    "SEQUENT.NS":"SeQuent Scientific","SHARDACROP.NS":"Sharda Cropchem",
    "SHILPAMED.NS":"Shilpa Medicare","SHOPERSTOP.NS":"Shoppers Stop",
    "SIGACHI.NS":"Sigachi Industries","SKIPPER.NS":"Skipper Ltd",
    "SOLARA.NS":"Solara Active Pharma","SPANDANA.NS":"Spandana Sphoorty",
    "SPARC.NS":"Sun Pharma Advanced Research","STLTECH.NS":"STL Technology",
    "SUBROS.NS":"Subros Ltd","SUDARSCHEM.NS":"Sudarshan Chemical",
    "SUMICHEM.NS":"Sumitomo Chemical India","SURYAROSNI.NS":"Surya Roshni",
    "SUVENPHAR.NS":"Suven Pharmaceuticals","SYMPHONY.NS":"Symphony Ltd",
    "TANLA.NS":"Tanla Platforms","TATAINVEST.NS":"Tata Investment Corp",
    "TCIEXP.NS":"TCI Express","TCNSBRANDS.NS":"TCNS Clothing",
    "TDPOWERSYS.NS":"TD Power Systems","THYROCARE.NS":"Thyrocare Technologies",
    "TINPLATE.NS":"Tinplate Company of India","TITAGARH.NS":"Titagarh Rail Systems",
    "UNIPARTS.NS":"Uniparts India","UTIAMC.NS":"UTI AMC","VARROC.NS":"Varroc Engineering",
    "VGUARD.NS":"V-Guard Industries","VIDHIING.NS":"Vidhi Specialty Food",
    "VIPIND.NS":"VIP Industries","VMART.NS":"V-Mart Retail","VSTIND.NS":"VST Industries",
    "WABAG.NS":"VA Tech Wabag","WEBELSOLAR.NS":"Webel Solar",
    "XCHANGING.NS":"Xchanging Solutions","YATHARTH.NS":"Yatharth Hospital",
    "ZENSARTECH.NS":"Zensar Technologies",
    # Extra
    "PAYTM.NS":"One97 Communications (Paytm)","NYKAA.NS":"FSN E-Commerce (Nykaa)",
    "POLICYBZR.NS":"PB Fintech (PolicyBazaar)","CARTRADE.NS":"CarTrade Tech",
    "MAMAEARTH.NS":"Honasa Consumer (Mamaearth)","IXIGO.NS":"Le Travenues (Ixigo)",
    "SWIGGY.NS":"Bundl Technologies (Swiggy)","FIRSTCRY.NS":"Brainbees Solutions (FirstCry)",
    "AWFIS.NS":"Awfis Space Solutions","BANKINDIA.NS":"Bank of India",
    "MAHABANK.NS":"Bank of Maharashtra","UCOBANK.NS":"UCO Bank",
    "RVNL.NS":"Rail Vikas Nigam","IRFC.NS":"Indian Railway Finance Corp",
    "IREDA.NS":"Indian Renewable Energy Dev Agency","SJVN.NS":"SJVN Ltd",
    "NHPC.NS":"NHPC Ltd","PFC.NS":"Power Finance Corporation",
    "NALCO.NS":"National Aluminium Company","BEML.NS":"BEML Ltd",
    "GRSE.NS":"Garden Reach Shipbuilders","COCHINSHIP.NS":"Cochin Shipyard",
    "MAZAGON.NS":"Mazagon Dock Shipbuilders","DATAPATTNS.NS":"Data Patterns India",
    "IDEAFORGE.NS":"ideaForge Technology","GREENPANEL.NS":"Greenpanel Industries",
    "WEBSOL.NS":"Websol Energy System","WAAREEENER.NS":"Waaree Energies",
    "SUZLON.NS":"Suzlon Energy","CESC.NS":"CESC Ltd",
    "INDHOTEL.NS":"Indian Hotels (Taj)","EIHOTEL.NS":"EIH Ltd (Oberoi)",
    "MAHINDCIE.NS":"Mahindra CIE Automotive","GSFC.NS":"Gujarat State Fertilizers",
    "COROMANDEL.NS":"Coromandel International","GODREJAGRO.NS":"Godrej Agrovet",
    "WELSPUNLIV.NS":"Welspun Living","TRIDENT.NS":"Trident Ltd",
    "VARDHMAN.NS":"Vardhman Textiles","RAYMOND.NS":"Raymond Ltd",
    "ARVIND.NS":"Arvind Ltd","BLUEDART.NS":"Blue Dart Express",
    "GATI.NS":"Gati Ltd","MAHLOG.NS":"Mahindra Logistics","VRL.NS":"VRL Logistics",
    "SUNTV.NS":"Sun TV Network","ZEEL.NS":"Zee Entertainment",
    "PVRINOX.NS":"PVR Inox","DMART.NS":"Avenue Supermarts (DMart)",
    "AAVAS.NS":"Aavas Financiers","VINATIORGA.NS":"Vinati Organics",
}
